.globl _boot
_boot:
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	add x0, x0, x0
	.word 0xdeadbeef
