TOP_MODULE=rom_unit_test
OUTDIR=out
PROJECT_ROOT=../../
CPP_SOURCE_FILES:=$(TOP_MODULE)_sim.cpp


REQUIRE_BOOTROM:=1
-include $(PROJECT_ROOT)/storm.mk
BOOTROM_DIR=bootrom
-include ../common/unittest.mk
