#ifndef CONSTS_H
#define CONSTS_H

#define NUMBER_OF_ROB 16
#define ROB_NUM_OF_ENTRIES NUMBER_OF_ROB.0
#define LOG2_ROB_NUM_OF_ENTRIES _int(_log10(ROB_NUM_OF_ENTRIES)/_log10(2.0))
#define ROB_TAG_SIZE LOG2_ROB_NUM_OF_ENTRIES+2

#define NUMBER_OF_RS 4
#define RS_NUM_OF_ENTRIES NUMBER_OF_RS.0
#define LOG2_RS_NUM_OF_ENTRIES _int(_log10(RS_NUM_OF_ENTRIES)/_log10(2.0))

#define NUMBER_OF_RS_IN_ORDER 4
#define RS_IN_ORDER_NUM_OF_ENTRIES NUMBER_OF_RS_IN_ORDER.0
#define LOG2_RS_IN_ORDER_NUM_OF_ENTRIES _int(_log10(RS_IN_ORDER_NUM_OF_ENTRIES)/_log10(2.0))

#endif
